# -*- coding: utf-8 -*-
"""Classification Fifa world cup team.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BW4v-FvVn5IN7ivkcpTB7mKYlsQ-5UA
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df = pd.read_csv('train.csv')

leakage_cols = ['finalist', 'semi_finalist', 'quarter_finalist']
df = df.drop(columns=leakage_cols)

df.head()

"""## Data Cleaning and Preprocessing"""

# Check for duplicate rows and remove them
print(f"Number of duplicate rows before dropping: {df.duplicated().sum()}")
df.drop_duplicates(inplace=True)
print(f"Number of duplicate rows after dropping: {df.duplicated().sum()}")

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

for col in numeric_cols:
    if col != 'winner':
        df[col] = df[col].fillna(df[col].median())
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.describe()

# Display dataset information after handling missing values
print("\n--- Dataset Information After Cleaning ---")
df.info()

"""## Exploratory Data Analysis (EDA)

Let's explore the data to understand its distribution, relationships, and potential patterns through various visualizations.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Plot the distribution of the target variable (winner)
plt.figure(figsize=(6, 4))
sns.countplot(x='winner', data=df)
plt.title('Distribution of Target Variable (Winner)')
plt.xlabel('Winner (0: No, 1: Yes)')
plt.ylabel('Count')
plt.show()

# Plot distribution of 'goals_scored_last_4y'
plt.figure(figsize=(8, 5))
sns.histplot(df['goals_scored_last_4y'], kde=True)
plt.title('Distribution of Goals Scored Last 4 Years')
plt.xlabel('Goals Scored')
plt.ylabel('Frequency')
plt.show()

# Plot distribution of 'fifa_rank_pre_tournament'
plt.figure(figsize=(8, 5))
sns.histplot(df['fifa_rank_pre_tournament'], kde=True)
plt.title('Distribution of FIFA Rank Pre-Tournament')
plt.xlabel('FIFA Rank')
plt.ylabel('Frequency')
plt.show()

# Plot count of 'continent'
plt.figure(figsize=(10, 6))
sns.countplot(y='continent', data=df, order=df['continent'].value_counts().index)
plt.title('Count of Teams by Continent')
plt.xlabel('Count')
plt.ylabel('Continent')
plt.show()

# Calculate and plot the correlation matrix for numerical features
numerical_df = df.select_dtypes(include=['int64', 'float64'])
plt.figure(figsize=(15, 12))
sns.heatmap(numerical_df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df['winner'])
train, val = train_test_split(train, test_size=0.2, random_state=42, stratify=train['winner'])

print(f"Jumlah data latihan  : {len(train)} baris")
print(f"Jumlah data validasi : {len(val)} baris")
print(f"Jumlah data uji      : {len(test)} baris")

def df_to_dataset(dataframe, shuffle=True, batch_size=32):
    dataframe = dataframe.copy()
    labels = dataframe.pop('winner')
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
    if shuffle:
        ds = ds.shuffle(buffer_size=len(dataframe))
    ds = ds.batch(batch_size)
    return ds

demo_batch_size = 5
demo_ds = df_to_dataset(train, batch_size=demo_batch_size)

[(feature_batch, label_batch)] = demo_ds.take(1)

print("--- DAFTAR FITUR YANG BERHASIL DI-BATCH ---")
print(list(feature_batch.keys()))

print("\n--- VISUALISASI ISI FITUR NUMERIK ('goals_scored_last_4y') DALAM BATCH ---")
print(feature_batch['goals_scored_last_4y'])

print("\n--- VISUALISASI ISI TARGET / LABEL ---")
print(label_batch)

all_inputs = []
encoded_features = []

for header in numeric_cols:
    if header != 'winner':
        numeric_col = tf.keras.Input(shape=(1,), name=header)
        normalization_layer = tf.keras.layers.Normalization()
        normalization_layer.adapt(train[header].to_numpy().reshape(-1, 1))
        encoded_numeric_col = normalization_layer(numeric_col)
        all_inputs.append(numeric_col)
        encoded_features.append(encoded_numeric_col)

for header in categorical_cols:
    categorical_col = tf.keras.Input(shape=(1,), name=header, dtype='string')
    lookup = tf.keras.layers.StringLookup(vocabulary=train[header].unique())
    encoded_categorical_col = lookup(categorical_col)
    encoding = tf.keras.layers.CategoryEncoding(num_tokens=lookup.vocabulary_size(), output_mode="binary")
    encoded_categorical_col = encoding(encoded_categorical_col)
    all_inputs.append(categorical_col)
    encoded_features.append(encoded_categorical_col)

all_features = tf.keras.layers.concatenate(encoded_features)
x = tf.keras.layers.Dense(32, activation="relu")(all_features)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.Dense(16, activation="relu")(x)
output = tf.keras.layers.Dense(1, activation="sigmoid")(x)

model = tf.keras.Model(all_inputs, output)

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])

# Mengembalikan ukuran batch standar untuk training sesungguhnya
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

neg, pos = np.bincount(train['winner'])
total = neg + pos
weight_for_0 = (1 / neg) * (total / 2.0)
weight_for_1 = (1 / pos) * (total / 2.0)
class_weight = {0: weight_for_0, 1: weight_for_1}

train_history = model.fit(train_ds,
                          validation_data=val_ds,
                          epochs=20,
                          class_weight=class_weight)

def visualize_training(history):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    ax1.plot(history.history['accuracy'], label='Akurasi Latih', color='blue')
    ax1.plot(history.history['val_accuracy'], label='Akurasi Validasi', color='orange')
    ax1.set_title('Model Accuracy')
    ax1.set_ylabel('Accuracy')
    ax1.set_xlabel('Epoch')
    ax1.legend(loc='lower right')
    ax1.grid(True)

    ax2.plot(history.history['loss'], label='Loss Latih', color='blue')
    ax2.plot(history.history['val_loss'], label='Loss Validasi', color='orange')
    ax2.set_title('Model Loss')
    ax2.set_ylabel('Loss')
    ax2.set_xlabel('Epoch')
    ax2.legend(loc='upper right')
    ax2.grid(True)

    plt.show()

visualize_training(train_history)

loss, accuracy = model.evaluate(test_ds)
print(f"\nHasil Evaluasi Akhir - Loss: {loss:.4f}, Akurasi: {accuracy * 100:.2f}%")
